<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Gripper macro -->
  <xacro:macro name="gripper" params="prefix parent *origin">
    
    <!-- Properties -->
    <xacro:property name="gripper_base_length" value="0.10" />
    <xacro:property name="gripper_base_width" value="0.10" />
    <xacro:property name="gripper_base_height" value="0.05" />
    
    <xacro:property name="finger_length" value="0.10" />
    <xacro:property name="finger_width" value="0.01" />
    <xacro:property name="finger_height" value="0.015" />
    
    <xacro:property name="finger_mass" value="0.01" />
    <xacro:property name="gripper_base_mass" value="0.05" />

    <!-- Gripper base link -->
    <link name="${prefix}gripper_base_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="${gripper_base_mass}" />
        <inertia
          ixx="${gripper_base_mass * (gripper_base_width*gripper_base_width + gripper_base_height*gripper_base_height) / 12.0}"
          ixy="0.0"
          ixz="0.0"
          iyy="${gripper_base_mass * (gripper_base_length*gripper_base_length + gripper_base_height*gripper_base_height) / 12.0}"
          iyz="0.0"
          izz="${gripper_base_mass * (gripper_base_length*gripper_base_length + gripper_base_width*gripper_base_width) / 12.0}" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${gripper_base_length} ${gripper_base_width} ${gripper_base_height}" />
        </geometry>
        <material name="gripper_base_material">
          <color rgba="0.5 0.5 0.5 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${gripper_base_length} ${gripper_base_width} ${gripper_base_height}" />
        </geometry>
      </collision>
    </link>

    <!-- Gripper base joint -->
    <joint name="${prefix}gripper_base_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}" />
      <child link="${prefix}gripper_base_link" />
    </joint>

    <!-- Left finger link -->
    <link name="${prefix}left_finger_link">
      <inertial>
        <origin xyz="${finger_length/2.0} 0 0" rpy="0 0 0" />
        <mass value="${finger_mass}" />
        <inertia
          ixx="${finger_mass * (finger_width*finger_width + finger_height*finger_height) / 12.0}"
          ixy="0.0"
          ixz="0.0"
          iyy="${finger_mass * (finger_length*finger_length + finger_height*finger_height) / 12.0}"
          iyz="0.0"
          izz="${finger_mass * (finger_length*finger_length + finger_width*finger_width) / 12.0}" />
      </inertial>
      <visual>
        <origin xyz="${finger_length/2.0} 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${finger_length} ${finger_width} ${finger_height}" />
        </geometry>
        <material name="finger_material">
          <color rgba="0.8 0.8 0.8 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="${finger_length/2.0} 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${finger_length} ${finger_width} ${finger_height}" />
        </geometry>
      </collision>
    </link>

    <!-- Left finger joint -->
    <joint name="${prefix}left_finger_joint" type="prismatic">
      <origin xyz="${gripper_base_length/2.0} ${finger_width/2.0} 0" rpy="0 0 0" />
      <parent link="${prefix}gripper_base_link" />
      <child link="${prefix}left_finger_link" />
      <axis xyz="0 1 0" />
      <limit lower="0.0" upper="0.05" effort="10" velocity="0.5" />
    </joint>

    <!-- Right finger link -->
    <link name="${prefix}right_finger_link">
      <inertial>
        <origin xyz="${finger_length/2.0} 0 0" rpy="0 0 0" />
        <mass value="${finger_mass}" />
        <inertia
          ixx="${finger_mass * (finger_width*finger_width + finger_height*finger_height) / 12.0}"
          ixy="0.0"
          ixz="0.0"
          iyy="${finger_mass * (finger_length*finger_length + finger_height*finger_height) / 12.0}"
          iyz="0.0"
          izz="${finger_mass * (finger_length*finger_length + finger_width*finger_width) / 12.0}" />
      </inertial>
      <visual>
        <origin xyz="${finger_length/2.0} 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${finger_length} ${finger_width} ${finger_height}" />
        </geometry>
        <material name="finger_material">
          <color rgba="0.8 0.8 0.8 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="${finger_length/2.0} 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${finger_length} ${finger_width} ${finger_height}" />
        </geometry>
      </collision>
    </link>

    <!-- Right finger joint -->
    <joint name="${prefix}right_finger_joint" type="prismatic">
      <origin xyz="${gripper_base_length/2.0} ${-finger_width/2.0} 0" rpy="0 0 0" />
      <parent link="${prefix}gripper_base_link" />
      <child link="${prefix}right_finger_link" />
      <axis xyz="0 -1 0" />
      <limit lower="0.0" upper="0.05" effort="10" velocity="0.5" />
      <mimic joint="${prefix}left_finger_joint" multiplier="1" offset="0" />
    </joint>

    <!-- Gripper tip link (tool center point) -->
    <link name="${prefix}gripper_tip_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="0.001" />
        <inertia ixx="1e-8" ixy="0.0" ixz="0.0" iyy="1e-8" iyz="0.0" izz="1e-8" />
      </inertial>
    </link>

    <!-- Gripper tip joint -->
    <joint name="${prefix}gripper_tip_joint" type="fixed">
      <origin xyz="${gripper_base_length/2.0 + finger_length} 0 0" rpy="0 0 0" />
      <parent link="${prefix}gripper_base_link" />
      <child link="${prefix}gripper_tip_link" />
    </joint>

  </xacro:macro>

</robot>
